#!/usr/bin/env php
<?php

$development = file_exists(__DIR__ . '/config/console-local.php');

defined('YII_DEBUG') or define('YII_DEBUG', $development);
defined('YII_ENV') or define('YII_ENV', $development ? 'dev' : 'prod');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

if ($development) {

    $config = yii\helpers\ArrayHelper::merge(
        require(__DIR__ . '/config/common.php'),
        require(__DIR__ . '/config/console.php'),
        require(__DIR__ . '/config/console-local.php')
    );

} else {

    $config = yii\helpers\ArrayHelper::merge(
        require(__DIR__ . '/config/common.php'),
        require(__DIR__ . '/config/console.php')
    );

}

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
